/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    IMdiArrowUp: typeof import('~icons/mdi/arrow-up')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IMdiFloppy: typeof import('~icons/mdi/floppy')['default']
    IMdiHeart: typeof import('~icons/mdi/heart')['default']
    IMdiTrash: typeof import('~icons/mdi/trash')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
