/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiArrow: typeof import('~icons/mdi/arrow')['default']
    IMdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    IMdiArrowUp: typeof import('~icons/mdi/arrow-up')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
